"""Stable template type keys stored in EmailTemplate.type and used at send time."""

EMAIL_VERIFICATION = "EMAIL_VERIFICATION"
PASSWORD_RESET = "PASSWORD_RESET"

ORDER_RECEIVED = "ORDER_RECEIVED"
ORDER_CONFIRMED = "ORDER_CONFIRMED"
PAYMENT_SUBMITTED = "PAYMENT_SUBMITTED"
SUBSCRIPTION_PAYMENT = "SUBSCRIPTION_PAYMENT"
SUBSCRIPTION_ACTIVATED = "SUBSCRIPTION_ACTIVATED"
SUBSCRIPTION_CHANGED = "SUBSCRIPTION_CHANGED"
PLATFORM_NEW_SUBSCRIPTION = "PLATFORM_NEW_SUBSCRIPTION"
TWO_FA_DISABLE = "TWO_FA_DISABLE"
TWO_FA_RECOVERY = "TWO_FA_RECOVERY"
# Reserved for a future email-OTP flow; no trigger wired while login uses TOTP only.
TWO_FA_CODE = "TWO_FA_CODE"
GENERIC_NOTIFICATION = "GENERIC_NOTIFICATION"
