# Generated by Django 5.2.12 on 2026-03-28 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(db_index=True, editable=False, help_text='Non-sequential public identifier (e.g. crr_xxx).', max_length=32, unique=True)),
                ('provider', models.CharField(choices=[('pathao', 'Pathao'), ('steadfast', 'Steadfast')], max_length=20)),
                ('api_key_encrypted', models.TextField(help_text='Fernet-encrypted API key.')),
                ('secret_key_encrypted', models.TextField(blank=True, default='', help_text='Fernet-encrypted secret key (Steadfast).')),
                ('access_token_encrypted', models.TextField(blank=True, default='', help_text='Fernet-encrypted access/bearer token (Pathao).')),
                ('refresh_token', models.TextField(blank=True, default='')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='couriers', to='stores.store')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
