# Generated by Django 5.2.12 on 2026-03-29 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, default='', help_text='URL slug per store; generated from name (unique per store).', max_length=100),
        ),
    ]
