# Generated by Django 5.2.12 on 2026-03-18 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, help_text='Dynamic extra fields per extra_field_schema (e.g. color, warranty).'),
        ),
    ]
