# Generated by Django 5.2.12

from django.db import migrations


def migrate_brands_to_store(apps, schema_editor):
    """Migrate Brand rows to Store.brand_showcase JSON per store."""
    Brand = apps.get_model("products", "Brand")
    Store = apps.get_model("stores", "Store")

    for store in Store.objects.all():
        brands = Brand.objects.filter(store=store).order_by("brand_type", "order", "name")
        showcase = []
        for b in brands:
            image_url = b.image.url if b.image else None
            showcase.append({
                "name": b.name,
                "slug": b.slug,
                "image_url": image_url,
                "redirect_url": b.redirect_url,
                "brand_type": b.brand_type,
                "order": b.order,
                "is_active": b.is_active,
            })
        store.brand_showcase = showcase
        store.save(update_fields=["brand_showcase"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_add_extra_data_jsonb"),
        ("stores", "0008_add_brand_showcase_and_extra_field_schema"),
    ]

    operations = [
        migrations.RunPython(migrate_brands_to_store, noop),
    ]
