# Generated by Django 5.2.12 on 2026-03-18 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_migrate_brands_to_store_brand_showcase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
