# Generated by Django 5.2.13 on 2026-04-30 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_product_product_store_active_status_order_idx'),
        ('stores', '0003_storesettings_language'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['store', 'is_active', 'status', 'display_order'], name='prod_store_active_status_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['store', 'category', 'is_active', 'status'], name='prod_store_cat_active_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['store', 'created_at'], name='prod_store_created_idx'),
        ),
    ]
