# Generated by Django 5.2.12 on 2026-03-19 12:26

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(db_index=True, editable=False, help_text='Non-sequential public identifier (e.g. anl_xxx).', max_length=32, unique=True)),
                ('period_date', models.DateField(db_index=True)),
                ('orders_count', models.PositiveIntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('cart_items_count', models.PositiveIntegerField(default=0)),
                ('wishlist_items_count', models.PositiveIntegerField(default=0)),
                ('page_views', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('conversion_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='stores.store')),
            ],
            options={
                'verbose_name_plural': 'Store analytics',
                'ordering': ['-period_date'],
                'constraints': [models.UniqueConstraint(fields=('store', 'period_date'), name='uniq_storeanalytics_store_period')],
            },
        ),
    ]
