# Generated by Django 5.2.12 on 2026-03-28 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(db_index=True, editable=False, help_text='Non-sequential public identifier used in APIs and URLs (e.g. str_xxx).', max_length=32, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('store_type', models.CharField(blank=True, help_text='Store type/category (e.g. Fashion, Retail, E-commerce). Max 4 words.', max_length=60)),
                ('is_active', models.BooleanField(default=True)),
                ('owner_name', models.CharField(help_text='Full name of the store owner.', max_length=255)),
                ('owner_email', models.EmailField(help_text='Email address of the store owner.', max_length=254)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='stores/logos/')),
                ('currency', models.CharField(default='BDT', max_length=8)),
                ('currency_symbol', models.CharField(blank=True, default='৳', max_length=10)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['is_active', 'created_at'], name='stores_stor_is_acti_a0dd20_idx')],
            },
        ),
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modules_enabled', models.JSONField(blank=True, default=dict, help_text='Feature/module flags for this store (e.g. products, orders, reviews).')),
                ('low_stock_threshold', models.PositiveIntegerField(default=5, help_text='Default low-stock alert threshold for inventory.')),
                ('extra_field_schema', models.JSONField(blank=True, default=list, help_text='Extra field definitions for product, customer, order: [{id, entityType, name, fieldType, required, order, options}]')),
                ('email_notify_owner_on_order_received', models.BooleanField(default=False, help_text='Premium: send email to store when a new order is placed.')),
                ('email_customer_on_order_confirmed', models.BooleanField(default=False, help_text='Premium: email customer when order is confirmed (send-to-courier).')),
                ('public_api_enabled', models.BooleanField(default=False, help_text='Allow public storefront read endpoints without API key for this store.')),
                ('storefront_public', models.JSONField(blank=True, default=dict, help_text='Public storefront-only data: theme_settings, country, seo, policy_urls, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='stores.store')),
            ],
            options={
                'verbose_name_plural': 'Store settings',
            },
        ),
        migrations.CreateModel(
            name='StoreApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(db_index=True, editable=False, help_text='Non-sequential public identifier (e.g. sak_xxx).', max_length=32, unique=True)),
                ('key_hash', models.CharField(db_index=True, help_text='HMAC-SHA256 digest of API key material.', max_length=64, unique=True)),
                ('key_prefix', models.CharField(blank=True, default='', max_length=16)),
                ('key_last4', models.CharField(blank=True, default='', max_length=4)),
                ('label', models.CharField(blank=True, default='', max_length=80)),
                ('key_type', models.CharField(choices=[('public', 'Public'), ('secret', 'Secret')], db_index=True, default='public', max_length=16)),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='stores.store')),
            ],
            options={
                'indexes': [models.Index(fields=['store', 'is_active', 'created_at'], name='stores_stor_store_i_d05ae1_idx')],
            },
        ),
        migrations.CreateModel(
            name='StoreDeletionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(db_index=True, editable=False, help_text='Non-sequential public identifier (e.g. dlj_xxx).', max_length=32, unique=True)),
                ('store_public_id_snapshot', models.CharField(db_index=True, help_text='Store public_id snapshot taken at deletion request time.', max_length=32)),
                ('store_id_snapshot', models.BigIntegerField(db_index=True, help_text='Store primary key snapshot taken at deletion request time.')),
                ('celery_task_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('current_step', models.CharField(blank=True, default='', max_length=120)),
                ('redirect_route', models.CharField(default='/onboarding', help_text='Frontend route to redirect after deletion is finalized.', max_length=64)),
                ('next_store_public_id', models.CharField(blank=True, help_text='Optional next active store public_id for the issuing JWTs.', max_length=32, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_deletion_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='stores_stor_user_id_f7a254_idx')],
            },
        ),
        migrations.CreateModel(
            name='StoreMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(db_index=True, editable=False, help_text='Non-sequential public identifier used in APIs and URLs (e.g. mbr_xxx).', max_length=32, unique=True)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('staff', 'Staff')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='stores.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['store', 'role'], name='stores_stor_store_i_845485_idx'), models.Index(fields=['user', 'created_at'], name='stores_stor_user_id_434953_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'store'), name='uniq_store_membership_user_store')],
            },
        ),
    ]
