# Generated by Django 5.2.12 on 2026-03-19 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(db_index=True, editable=False, help_text='Non-sequential public identifier used in APIs and URLs (e.g. str_xxx).', max_length=32, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('store_type', models.CharField(blank=True, help_text='Store type/category (e.g. Fashion, Retail, E-commerce). Max 4 words.', max_length=60)),
                ('domain', models.CharField(blank=True, help_text='Full domain or host used to route requests to this store. Set via Settings > Networking.', max_length=255, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('owner_name', models.CharField(help_text='Full name of the store owner.', max_length=255)),
                ('owner_email', models.EmailField(help_text='Email address of the store owner.', max_length=254)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='stores/logos/')),
                ('currency', models.CharField(default='BDT', max_length=8)),
                ('currency_symbol', models.CharField(blank=True, default='৳', max_length=10)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('brand_showcase', models.JSONField(blank=True, default=list, help_text='Homepage brand cards: name, slug, image_url, redirect_url, brand_type, order, is_active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['domain'], name='stores_stor_domain_9b7928_idx'), models.Index(fields=['is_active', 'created_at'], name='stores_stor_is_acti_a0dd20_idx')],
            },
        ),
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modules_enabled', models.JSONField(blank=True, default=dict, help_text='Feature/module flags for this store (e.g. products, orders, reviews).')),
                ('low_stock_threshold', models.PositiveIntegerField(default=5, help_text='Default low-stock alert threshold for inventory.')),
                ('extra_field_schema', models.JSONField(blank=True, default=list, help_text='Extra field definitions for product, customer, order: [{id, entityType, name, fieldType, required, order, options}]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='stores.store')),
            ],
            options={
                'verbose_name_plural': 'Store settings',
            },
        ),
        migrations.CreateModel(
            name='StoreMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('staff', 'Staff')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='stores.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['store', 'role'], name='stores_stor_store_i_845485_idx'), models.Index(fields=['user', 'created_at'], name='stores_stor_user_id_434953_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'store'), name='uniq_store_membership_user_store')],
            },
        ),
    ]
