# Generated by Django 5.2.12 on 2026-03-28 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storesettings',
            name='modules_enabled',
            field=models.JSONField(blank=True, default=dict, help_text='Feature/module flags for this store (e.g. products, orders).'),
        ),
    ]
