# Generated by Django 5.2.12 on 2026-03-18 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='store',
            name='admin_name',
            field=models.CharField(blank=True, default='', help_text='Display name in dashboard sidebar (defaults to name if empty).', max_length=100),
        ),
        migrations.AddField(
            model_name='store',
            name='admin_subtitle',
            field=models.CharField(blank=True, default='', help_text='Subtitle or tagline (e.g. category, type).', max_length=200),
        ),
        migrations.AddField(
            model_name='store',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='store',
            name='currency_symbol',
            field=models.CharField(blank=True, default='$', max_length=10),
        ),
        migrations.AddField(
            model_name='store',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='store',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='stores/logos/'),
        ),
        migrations.AddField(
            model_name='store',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
