# Generated by Django 5.2.12 on 2026-03-29 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_alter_storesettings_email_customer_on_order_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storesettings',
            name='storefront_public',
            field=models.JSONField(blank=True, default=dict, help_text='Public storefront-only data: theme_settings, country, seo, policy_urls, social_links, etc.'),
        ),
    ]
