# Generated by Django 5.2.12 on 2026-03-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_add_branding_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='admin_name',
            field=models.CharField(blank=True, default='', help_text='Display name in dashboard sidebar (defaults to name if empty).', max_length=100, verbose_name='Store display name'),
        ),
    ]
