# Generated by Django 5.2.12 on 2026-03-26 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_storeapikey'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='storeapikey',
            new_name='stores_stor_store_i_d05ae1_idx',
            old_name='stores_stor_store_i_2527eb_idx',
        ),
    ]
