# Generated by Django 5.2.12 on 2026-03-26 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_remove_storeapikey_unique_active'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='store',
            name='stores_stor_domain_9b7928_idx',
        ),
        migrations.RemoveField(
            model_name='store',
            name='domain',
        ),
        migrations.DeleteModel(
            name='Domain',
        ),
    ]
