# Generated by Django 5.2.12 on 2026-03-26 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0007_storeapikey_last_used_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeapikey',
            name='key_hash',
            field=models.CharField(db_index=True, help_text='HMAC-SHA256 digest of API key material.', max_length=64, unique=True),
        ),
    ]
