# Generated by Django 5.2.12 on 2026-03-18 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0007_currency_bdt_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='brand_showcase',
            field=models.JSONField(blank=True, default=list, help_text='Homepage brand cards: name, slug, image_url, redirect_url, brand_type, order, is_active'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='extra_field_schema',
            field=models.JSONField(blank=True, default=list, help_text='Extra field definitions for product, customer, order: [{id, entityType, name, fieldType, required, order, options}]'),
        ),
    ]
