# Generated by Django 5.2.12 on 2026-04-07 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0009_rename_stores_stord_store_i_7c8f9a_idx_stores_stor_store_i_c426f0_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='lifecycle_version',
            field=models.PositiveIntegerField(default=0, help_text='Monotonic counter incremented on every status transition; guards Celery jobs.'),
        ),
        migrations.AddField(
            model_name='storedeletionjob',
            name='lifecycle_version_snapshot',
            field=models.PositiveIntegerField(default=0, help_text='Store lifecycle_version at scheduling time; worker aborts if mismatch.'),
        ),
        migrations.AlterField(
            model_name='storelifecycleauditlog',
            name='action',
            field=models.CharField(choices=[('STORE_REMOVE', 'Store remove'), ('STORE_DELETE_OTP_SENT', 'Delete OTP sent'), ('STORE_DELETE_SCHEDULED', 'Delete scheduled'), ('STORE_RESTORE', 'Store restore'), ('STORE_INACTIVITY_PENDING', 'Inactivity pending delete')], db_index=True, max_length=40),
        ),
    ]
