# Generated by Django 5.2.11 on 2026-03-16 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_activitylog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='core_activi_created_3d0bd9_idx',
            old_name='core_activi_created_7d4c0f_idx',
        ),
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='core_activi_entity__16bebb_idx',
            old_name='core_activi_entity__a9d251_idx',
        ),
    ]
