# Generated by Django 5.2.12 on 2026-03-28 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(db_index=True, editable=False, help_text='Non-sequential public identifier (e.g. ban_xxx).', max_length=32, unique=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(upload_to='banners/')),
                ('cta_text', models.CharField(blank=True, max_length=255)),
                ('cta_link', models.URLField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='stores.store')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
