# Generated by Django 5.2.12 on 2026-04-07

from django.db import migrations, models


def backfill_banner_placement_slots(apps, schema_editor):
    Banner = apps.get_model("banners", "Banner")
    for banner in Banner.objects.all().only("id", "placement_slots"):
        slots = getattr(banner, "placement_slots", None)
        if not slots or len(slots) == 0:
            banner.placement_slots = ["global_topbar"]
            banner.save(update_fields=["placement_slots"])


class Migration(migrations.Migration):
    dependencies = [
        ("banners", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="banner",
            name="placement_slots",
            field=models.JSONField(default=list),
        ),
        migrations.RunPython(backfill_banner_placement_slots, migrations.RunPython.noop),
    ]

