# Generated by Django 5.2.12 on 2026-03-28 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(db_index=True, editable=False, help_text='Non-sequential public identifier (e.g. mkt_xxx).', max_length=32, unique=True)),
                ('provider', models.CharField(choices=[('facebook', 'Facebook'), ('google_analytics', 'Google Analytics'), ('tiktok', 'TikTok')], max_length=20)),
                ('pixel_id', models.CharField(blank=True, default='', help_text='Tracking pixel / measurement ID (e.g. Facebook Pixel ID).', max_length=64)),
                ('access_token_encrypted', models.TextField(blank=True, default='', help_text='Fernet-encrypted access token.')),
                ('test_event_code', models.CharField(blank=True, default='', help_text='Optional test event code for validation (Facebook).', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_integrations', to='stores.store')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationEventSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_purchase', models.BooleanField(default=True)),
                ('track_initiate_checkout', models.BooleanField(default=True)),
                ('track_view_content', models.BooleanField(default=False)),
                ('track_page_view', models.BooleanField(default=False)),
                ('integration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='event_settings', to='marketing_integrations.marketingintegration')),
            ],
            options={
                'verbose_name_plural': 'Integration event settings',
            },
        ),
        migrations.AddConstraint(
            model_name='marketingintegration',
            constraint=models.UniqueConstraint(fields=('store', 'provider'), name='uniq_marketingintegration_store_provider'),
        ),
    ]
