# Generated by Django 5.2.13 on 2026-04-15 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_integrations', '0004_store_event_log'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='storeeventlog',
            new_name='marketing_i_store_i_3c7fcc_idx',
            old_name='marketing_in_store_i_7d1a11',
        ),
        migrations.RenameIndex(
            model_name='storeeventlog',
            new_name='marketing_i_store_i_723d84_idx',
            old_name='marketing_in_store_i_c0af0f',
        ),
    ]
