# Generated by Django 5.2.13 on 2026-04-22 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_integrations', '0006_integrationeventsettings_track_add_to_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='integrationeventsettings',
            name='track_search',
        ),
    ]
