# Generated by Django 5.2.12 on 2026-04-03 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('custom', 'Custom')], max_length=20)),
                ('public_id', models.CharField(db_index=True, editable=False, help_text='Non-sequential public identifier (e.g. act_xxx).', max_length=32, unique=True)),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.CharField(blank=True, default='', max_length=64)),
                ('summary', models.CharField(max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_activity_logs', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='stores.store')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='core_activi_created_3d0bd9_idx'), models.Index(fields=['entity_type', 'action', '-created_at'], name='core_activi_entity__16bebb_idx')],
            },
        ),
        migrations.CreateModel(
            name='TrashItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('product', 'Product'), ('order', 'Order')], db_index=True, max_length=20)),
                ('entity_id', models.CharField(db_index=True, help_text='Internal UUID of the deleted Product or Order.', max_length=36)),
                ('entity_public_id', models.CharField(blank=True, default='', help_text='Optional copy of entity public_id for debugging.', max_length=32)),
                ('snapshot_json', models.JSONField(help_text='Versioned snapshot for restore.')),
                ('deleted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('is_restored', models.BooleanField(db_index=True, default=False)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trash_items_deleted', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trash_items', to='stores.store')),
            ],
            options={
                'ordering': ['-deleted_at', '-id'],
                'indexes': [models.Index(fields=['store', 'expires_at', 'is_restored'], name='core_trashi_store_i_a062e7_idx'), models.Index(fields=['store', 'entity_type', '-deleted_at'], name='core_trashi_store_i_9d49d3_idx')],
            },
        ),
    ]
