# Generated by Django 5.2.12 on 2026-03-19 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(db_index=True, editable=False, help_text='Non-sequential public identifier (e.g. ntf_xxx).', max_length=32, unique=True)),
                ('text', models.CharField(max_length=500)),
                ('notification_type', models.CharField(choices=[('banner', 'Banner'), ('alert', 'Alert'), ('promo', 'Promotion')], default='banner', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('link_text', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower = first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(db_index=True, editable=False, help_text='Non-sequential public identifier (e.g. snt_xxx).', max_length=32, unique=True)),
                ('message_type', models.CharField(choices=[('new_order', 'New order'), ('new_customer', 'New customer'), ('low_stock', 'Product out of stock'), ('wishlist_add', 'Product added to wishlist'), ('contact_submission', 'Contact form submitted'), ('other', 'Other')], default='other', max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, help_text='Null = visible to all staff', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='system_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
