# Generated by Django 5.2.12 on 2026-03-23 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_system_notification_view_and_daily_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemnotificationview',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
