# Generated by Django 5.2.12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=60)),
                ("price", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("billing_cycle", models.CharField(choices=[("monthly", "Monthly"), ("yearly", "Yearly")], default="monthly", max_length=20)),
                ("max_stores", models.PositiveIntegerField(default=1, help_text="Maximum number of stores allowed for this plan.")),
                ("features", models.JSONField(blank=True, default=dict, help_text="Feature flags (e.g. advanced_analytics, priority_support).")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["price"],
            },
        ),
        migrations.AddIndex(
            model_name="plan",
            index=models.Index(fields=["is_active"], name="billing_pla_is_acti_8a1c2a_idx"),
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("active", "Active"), ("expired", "Expired"), ("canceled", "Canceled")], default="active", max_length=20)),
                ("billing_cycle", models.CharField(choices=[("monthly", "Monthly"), ("yearly", "Yearly")], default="monthly", max_length=20)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("auto_renew", models.BooleanField(default=False)),
                ("source", models.CharField(choices=[("payment", "Payment"), ("manual", "Manual"), ("trial", "Trial")], max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("plan", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="subscriptions", to="billing.plan")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="subscriptions", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(fields=["user"], name="billing_sub_user_id_2f3b4c_idx"),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(fields=["status"], name="billing_sub_status_1a2b3c_idx"),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(fields=["user", "status"], name="billing_sub_user_id_4d5e6f_idx"),
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="BDT", max_length=8)),
                ("status", models.CharField(choices=[("success", "Success"), ("failed", "Failed"), ("refunded", "Refunded")], max_length=20)),
                ("provider", models.CharField(choices=[("stripe", "Stripe"), ("paddle", "Paddle"), ("sslcommerz", "SSLCommerz"), ("manual", "Manual"), ("bkash", "bKash")], max_length=30)),
                ("transaction_id", models.CharField(blank=True, help_text="Provider transaction ID. Null for manual payments.", max_length=255, null=True, unique=True)),
                ("metadata", models.JSONField(blank=True, default=dict, help_text="Raw provider response or additional data.")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("subscription", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="payments", to="billing.subscription")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="payments", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["user"], name="billing_pay_user_id_7a8b9c_idx"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["status"], name="billing_pay_status_9d0e1f_idx"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["provider"], name="billing_pay_provide_2a3b4c_idx"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["created_at"], name="billing_pay_created_5b6c7d_idx"),
        ),
    ]
