# Generated by Django 5.2.13 on 2026-04-09 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Marketing/display only. Does not grant dashboard access.'),
        ),
    ]
