# Generated by Django 5.2.13 on 2026-04-09 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_plan_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='plan',
            field=models.ForeignKey(blank=True, help_text='Intended plan for this payment. Set during initiation; cleared when subscription is linked.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_payments', to='billing.plan'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('paddle', 'Paddle'), ('sslcommerz', 'SSLCommerz'), ('manual', 'Manual'), ('bkash', 'bKash'), ('nagad', 'Nagad')], max_length=30),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('refunded', 'Refunded')], max_length=20),
        ),
    ]
