# Generated by Django 5.2.12 on 2026-03-18 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_seed_plans'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='payment',
            new_name='billing_pay_user_id_09fdcc_idx',
            old_name='billing_pay_user_id_7a8b9c_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='billing_pay_status_b7739e_idx',
            old_name='billing_pay_status_9d0e1f_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='billing_pay_provide_6ea4b9_idx',
            old_name='billing_pay_provide_2a3b4c_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='billing_pay_created_a6e2cd_idx',
            old_name='billing_pay_created_5b6c7d_idx',
        ),
        migrations.RenameIndex(
            model_name='plan',
            new_name='billing_pla_is_acti_0aba70_idx',
            old_name='billing_pla_is_acti_8a1c2a_idx',
        ),
        migrations.RenameIndex(
            model_name='subscription',
            new_name='billing_sub_user_id_a87c1b_idx',
            old_name='billing_sub_user_id_2f3b4c_idx',
        ),
        migrations.RenameIndex(
            model_name='subscription',
            new_name='billing_sub_status_948046_idx',
            old_name='billing_sub_status_1a2b3c_idx',
        ),
        migrations.RenameIndex(
            model_name='subscription',
            new_name='billing_sub_user_id_fe5b98_idx',
            old_name='billing_sub_user_id_4d5e6f_idx',
        ),
    ]
