# Generated by Django 5.2.12 on 2026-03-18 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_feature_gate_json_structure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='features',
            field=models.JSONField(blank=True, default=dict, help_text='Structured config: {"limits": {"max_stores": N}, "features": {"advanced_analytics": bool, ...}}'),
        ),
    ]
