# Generated by Django 5.2.12 on 2026-04-03 13:20

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('products', '0001_initial'),
        ('shipping', '0001_initial'),
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderNumberCounter',
            fields=[
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='order_counter', serialize=False, to='stores.store')),
                ('next_value', models.PositiveBigIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_id', models.CharField(db_index=True, editable=False, help_text='Non-sequential public identifier (e.g. ord_xxx).', max_length=32, unique=True)),
                ('order_number', models.CharField(db_index=True, editable=False, max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('subtotal_before_discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sum of line list extended amounts (original_price × qty).', max_digits=12)),
                ('discount_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sum of per-line discount × qty.', max_digits=12)),
                ('subtotal_after_discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Merchandise total after discounts; equals sum of line_total.', max_digits=12)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('shipping_name', models.CharField(blank=True, max_length=255)),
                ('shipping_address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('district', models.CharField(blank=True, default='', max_length=100)),
                ('courier_provider', models.CharField(blank=True, default='', max_length=20)),
                ('courier_consignment_id', models.CharField(blank=True, default='', max_length=100)),
                ('sent_to_courier', models.BooleanField(default=False)),
                ('customer_confirmation_sent_at', models.DateTimeField(blank=True, help_text='Set when ORDER_CONFIRMED was sent after courier dispatch.', null=True)),
                ('pricing_snapshot', models.JSONField(blank=True, default=dict, help_text='JSON audit snapshot of order pricing breakdown (lines + rollups + shipping).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='customers.customer')),
                ('shipping_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='shipping.shippingmethod')),
                ('shipping_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='shipping.shippingrate')),
                ('shipping_zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='shipping.shippingzone')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='stores.store')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(db_index=True, editable=False, help_text='Non-sequential public identifier (e.g. oit_xxx).', max_length=32, unique=True)),
                ('product_name_snapshot', models.CharField(max_length=255)),
                ('variant_snapshot', models.CharField(blank=True, max_length=255, null=True)),
                ('unit_price_snapshot', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Final charged unit price at order time.', max_digits=10)),
                ('original_price', models.DecimalField(decimal_places=2, help_text='List/reference unit price frozen at order time.', max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Per unit: original_price − unit_price (may be negative for surcharges).', max_digits=10)),
                ('line_subtotal', models.DecimalField(decimal_places=2, help_text='original_price × quantity', max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, help_text='unit_price × quantity', max_digits=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='products.productvariant')),
            ],
        ),
        migrations.CreateModel(
            name='OrderAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('shipping', 'Shipping'), ('billing', 'Billing')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='orders.order')),
            ],
            options={
                'ordering': ['order', 'address_type'],
                'unique_together': {('order', 'address_type')},
            },
        ),
        migrations.CreateModel(
            name='StockRestoreLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('cancelled', 'Cancelled')], max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_restore_logs', to='orders.order')),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_restore_logs', to='orders.orderitem')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_restore_logs', to='stores.store')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('order', 'order_item', 'reason'), name='uniq_order_item_restore_reason')],
            },
        ),
    ]
