# Generated by Django 5.2.12 on 2026-03-18 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, help_text='Dynamic extra fields per extra_field_schema.'),
        ),
    ]
