# Generated by Cursor on 2026-04-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="flag",
            field=models.CharField(
                blank=True,
                choices=[
                    ("no_response", "No Response"),
                    ("call_later", "Call Later"),
                    ("wrong_number", "Wrong Number"),
                    ("busy", "Busy"),
                    ("high_priority", "High Priority"),
                ],
                db_index=True,
                default=None,
                max_length=32,
                null=True,
            ),
        ),
    ]

