# Generated by Django 5.2.12 on 2026-03-20 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_add_public_id_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='courier_consignment_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='courier_provider',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='courier_status',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='courier_tracking_code',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='sent_to_courier',
            field=models.BooleanField(default=False),
        ),
    ]
