# Generated by Django 5.2.12 on 2026-03-24 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_customer'),
        ('shipping', '0003_remove_shippingzone_delivery_areas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_area',
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='shipping.shippingzone'),
        ),
    ]
