# Generated by Django 5.2.12 on 2026-03-29 18:55

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(db_index=True, editable=False, help_text='Non-sequential public identifier (e.g. smt_xxx).', max_length=32, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('method_type', models.CharField(choices=[('standard', 'Standard'), ('express', 'Express'), ('pickup', 'Pickup'), ('other', 'Other')], default='standard', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_methods', to='stores.store')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ShippingZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(db_index=True, editable=False, help_text='Non-sequential public identifier (e.g. szn_xxx).', max_length=32, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('estimated_delivery_text', models.CharField(blank=True, default='', help_text='Customer-facing delivery estimate (e.g. "1-2" days).', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_zones', to='stores.store')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ShippingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(db_index=True, editable=False, help_text='Non-sequential public identifier (e.g. srt_xxx).', max_length=32, unique=True)),
                ('rate_type', models.CharField(choices=[('flat', 'Flat rate'), ('weight', 'Per unit weight'), ('order_total', 'By order total')], default='flat', max_length=20)),
                ('min_order_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_order_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('shipping_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='shipping.shippingmethod')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_rates', to='stores.store')),
                ('shipping_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='shipping.shippingzone')),
            ],
            options={
                'ordering': ['shipping_method', 'shipping_zone'],
            },
        ),
        migrations.AddField(
            model_name='shippingmethod',
            name='zones',
            field=models.ManyToManyField(blank=True, help_text='Zones this method applies to; empty = all zones', related_name='shipping_methods', to='shipping.shippingzone'),
        ),
        migrations.AddIndex(
            model_name='shippingzone',
            index=models.Index(fields=['store', 'is_active', 'name'], name='shipping_sh_store_i_4abd35_idx'),
        ),
        migrations.AddConstraint(
            model_name='shippingzone',
            constraint=models.UniqueConstraint(fields=('store', 'name'), name='uniq_shipping_zone_store_name'),
        ),
        migrations.AddIndex(
            model_name='shippingrate',
            index=models.Index(fields=['store', 'is_active'], name='shipping_sh_store_i_7e6165_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingrate',
            index=models.Index(fields=['store', 'shipping_method', 'shipping_zone'], name='shipping_sh_store_i_7084fa_idx'),
        ),
        migrations.AddConstraint(
            model_name='shippingrate',
            constraint=models.UniqueConstraint(fields=('store', 'shipping_method', 'shipping_zone', 'rate_type', 'min_order_total', 'max_order_total'), name='uniq_shipping_rate_rule'),
        ),
        migrations.AddIndex(
            model_name='shippingmethod',
            index=models.Index(fields=['store', 'is_active', 'order'], name='shipping_sh_store_i_c8adda_idx'),
        ),
        migrations.AddConstraint(
            model_name='shippingmethod',
            constraint=models.UniqueConstraint(fields=('store', 'name'), name='uniq_shipping_method_store_name'),
        ),
    ]
