# Generated by Cursor on 2026-03-19

from django.db import migrations, models
import django.db.models.deletion


def _backfill_store(apps, schema_editor):
    Store = apps.get_model("stores", "Store")
    ShippingZone = apps.get_model("shipping", "ShippingZone")
    ShippingMethod = apps.get_model("shipping", "ShippingMethod")
    ShippingRate = apps.get_model("shipping", "ShippingRate")

    store = Store.objects.filter(is_active=True).order_by("id").first()
    if not store:
        return

    ShippingZone.objects.filter(store__isnull=True).update(store=store)
    ShippingMethod.objects.filter(store__isnull=True).update(store=store)
    ShippingRate.objects.filter(store__isnull=True).update(store=store)


class Migration(migrations.Migration):
    dependencies = [
        ("stores", "0001_initial"),
        ("shipping", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shippingzone",
            name="store",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shipping_zones",
                to="stores.store",
            ),
        ),
        migrations.AddField(
            model_name="shippingzone",
            name="delivery_areas",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated delivery areas (e.g. inside,outside). Blank = any.",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="shippingzone",
            name="districts",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated districts/cities this zone applies to (e.g. Dhaka,Chittagong). Blank = any.",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="shippingmethod",
            name="store",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shipping_methods",
                to="stores.store",
            ),
        ),
        migrations.AddField(
            model_name="shippingrate",
            name="store",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shipping_rates",
                to="stores.store",
            ),
        ),
        migrations.RunPython(_backfill_store, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="shippingzone",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shipping_zones",
                to="stores.store",
            ),
        ),
        migrations.AlterField(
            model_name="shippingmethod",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shipping_methods",
                to="stores.store",
            ),
        ),
        migrations.AlterField(
            model_name="shippingrate",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shipping_rates",
                to="stores.store",
            ),
        ),
        migrations.AddIndex(
            model_name="shippingzone",
            index=models.Index(fields=["store", "is_active", "name"], name="shipping_sh_store_i_8b3b41_idx"),
        ),
        migrations.AddConstraint(
            model_name="shippingzone",
            constraint=models.UniqueConstraint(fields=("store", "name"), name="uniq_shipping_zone_store_name"),
        ),
        migrations.AddIndex(
            model_name="shippingmethod",
            index=models.Index(fields=["store", "is_active", "order"], name="shipping_sh_store_i_8b68d2_idx"),
        ),
        migrations.AddConstraint(
            model_name="shippingmethod",
            constraint=models.UniqueConstraint(fields=("store", "name"), name="uniq_shipping_method_store_name"),
        ),
        migrations.AddIndex(
            model_name="shippingrate",
            index=models.Index(fields=["store", "is_active"], name="shipping_sh_store_i_4bf0d1_idx"),
        ),
        migrations.AddIndex(
            model_name="shippingrate",
            index=models.Index(fields=["store", "shipping_method", "shipping_zone"], name="shipping_sh_store_i_82e75d_idx"),
        ),
        migrations.AddConstraint(
            model_name="shippingrate",
            constraint=models.UniqueConstraint(
                fields=("store", "shipping_method", "shipping_zone", "rate_type", "min_order_total", "max_order_total"),
                name="uniq_shipping_rate_rule",
            ),
        ),
    ]

