# Generated by Cursor on 2026-03-19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shipping", "0002_store_scoping_and_destination_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shippingzone",
            name="country_codes",
        ),
    ]

