# Generated by Django 5.2.12 on 2026-03-24 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0002_repair_shippingzone_delivery_areas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingzone',
            name='delivery_areas',
        ),
        migrations.RemoveField(
            model_name='shippingzone',
            name='districts',
        ),
    ]
