# Generated by Django 5.2.12 on 2026-03-19 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0003_remove_country_codes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='shippingmethod',
            new_name='shipping_sh_store_i_c8adda_idx',
            old_name='shipping_sh_store_i_8b68d2_idx',
        ),
        migrations.RenameIndex(
            model_name='shippingrate',
            new_name='shipping_sh_store_i_7e6165_idx',
            old_name='shipping_sh_store_i_4bf0d1_idx',
        ),
        migrations.RenameIndex(
            model_name='shippingrate',
            new_name='shipping_sh_store_i_7084fa_idx',
            old_name='shipping_sh_store_i_82e75d_idx',
        ),
        migrations.RenameIndex(
            model_name='shippingzone',
            new_name='shipping_sh_store_i_4abd35_idx',
            old_name='shipping_sh_store_i_8b3b41_idx',
        ),
    ]
