# Generated by Django 5.2.12 on 2026-03-28 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(db_index=True, editable=False, help_text='Non-sequential public identifier (e.g. inv_xxx).', max_length=32, unique=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('low_stock_threshold', models.PositiveIntegerField(default=5, help_text='Alert when quantity falls at or below this value.')),
                ('is_tracked', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_records', to='products.product')),
                ('variant', models.OneToOneField(blank=True, help_text='Null for product-level stock; set for variant-level stock.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='products.productvariant')),
            ],
            options={
                'verbose_name_plural': 'Inventories',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(db_index=True, editable=False, help_text='Non-sequential public identifier (e.g. stm_xxx).', max_length=32, unique=True)),
                ('change', models.IntegerField(help_text='Positive for increase, negative for decrease.')),
                ('reason', models.CharField(choices=[('adjustment', 'Manual adjustment'), ('sale', 'Sale / order'), ('return', 'Return / refund'), ('restock', 'Restock'), ('damaged', 'Damaged / lost'), ('other', 'Other')], default='adjustment', max_length=20)),
                ('source', models.CharField(choices=[('order', 'Order lifecycle'), ('admin', 'Admin inventory update'), ('system', 'System process')], default='system', max_length=20)),
                ('reference_id', models.CharField(blank=True, default='', max_length=100)),
                ('reference', models.CharField(blank=True, help_text='e.g. order number, note', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.inventory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.UniqueConstraint(fields=('product', 'variant'), name='inventory_product_variant_unique'),
        ),
    ]
