# Generated by Django 5.2.12 on 2026-03-18 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('orders', '0001_initial'),
        ('products', '0002_alter_product_category_and_more'),
        ('stores', '0007_currency_bdt_defaults'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('product', 'Product'), ('variant', 'Product variant'), ('category', 'Category'), ('customer', 'Customer'), ('order', 'Order')], max_length=20)),
                ('key', models.SlugField(help_text='Internal key used in APIs (e.g. color, size).', max_length=100)),
                ('label', models.CharField(help_text='Human-readable label for dashboards/frontends.', max_length=255)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('bool', 'Boolean'), ('date', 'Date'), ('select', 'Select'), ('multiselect', 'Multi select')], max_length=20)),
                ('required', models.BooleanField(default=False)),
                ('filterable', models.BooleanField(default=False, help_text='Whether this attribute should be usable in filters/facets.')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('options', models.JSONField(blank=True, help_text='For select/multiselect types: list of allowed options.', null=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_definitions', to='stores.store')),
            ],
            options={
                'ordering': ['store', 'entity_type', 'order', 'key'],
            },
        ),
        migrations.CreateModel(
            name='CategoryAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.TextField(blank=True, null=True)),
                ('value_number', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('value_bool', models.BooleanField(blank=True, null=True)),
                ('value_date', models.DateField(blank=True, null=True)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_values', to='attributes.attributedefinition')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='products.category')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.TextField(blank=True, null=True)),
                ('value_number', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('value_bool', models.BooleanField(blank=True, null=True)),
                ('value_date', models.DateField(blank=True, null=True)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_values', to='attributes.attributedefinition')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.TextField(blank=True, null=True)),
                ('value_number', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('value_bool', models.BooleanField(blank=True, null=True)),
                ('value_date', models.DateField(blank=True, null=True)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_values', to='attributes.attributedefinition')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.TextField(blank=True, null=True)),
                ('value_number', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('value_bool', models.BooleanField(blank=True, null=True)),
                ('value_date', models.DateField(blank=True, null=True)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_values', to='attributes.attributedefinition')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='VariantAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.TextField(blank=True, null=True)),
                ('value_number', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('value_bool', models.BooleanField(blank=True, null=True)),
                ('value_date', models.DateField(blank=True, null=True)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_values', to='attributes.attributedefinition')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_attribute_values', to='products.productvariant')),
            ],
        ),
        migrations.AddConstraint(
            model_name='attributedefinition',
            constraint=models.UniqueConstraint(fields=('store', 'entity_type', 'key'), name='uniq_attrdef_store_entity_key'),
        ),
        migrations.AddConstraint(
            model_name='categoryattributevalue',
            constraint=models.UniqueConstraint(fields=('entity', 'definition'), name='uniq_category_attr_entity_definition'),
        ),
        migrations.AddConstraint(
            model_name='customerattributevalue',
            constraint=models.UniqueConstraint(fields=('entity', 'definition'), name='uniq_customer_attr_entity_definition'),
        ),
        migrations.AddConstraint(
            model_name='orderattributevalue',
            constraint=models.UniqueConstraint(fields=('entity', 'definition'), name='uniq_order_attr_entity_definition'),
        ),
        migrations.AddConstraint(
            model_name='productattributevalue',
            constraint=models.UniqueConstraint(fields=('entity', 'definition'), name='uniq_product_attr_entity_definition'),
        ),
        migrations.AddConstraint(
            model_name='variantattributevalue',
            constraint=models.UniqueConstraint(fields=('entity', 'definition'), name='uniq_variant_attr_entity_definition'),
        ),
    ]
