# Generated by Django 5.2.12 on 2026-03-21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_add_proxy_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserTwoFactor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("secret_encrypted", models.TextField(blank=True, default="")),
                ("pending_secret_encrypted", models.TextField(blank=True, default="")),
                ("is_enabled", models.BooleanField(default=False)),
                ("failed_attempts", models.PositiveIntegerField(default=0)),
                ("locked_until", models.DateTimeField(blank=True, null=True)),
                ("last_used_step", models.BigIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="two_factor_profile", to="accounts.user")),
            ],
            options={
                "indexes": [models.Index(fields=["is_enabled"], name="accounts_usi_is_enab_aec89c_idx")],
            },
        ),
        migrations.CreateModel(
            name="UserTwoFactorChallenge",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("flow", models.CharField(choices=[("login", "Login"), ("register", "Register"), ("switch_store", "Switch Store")], max_length=20)),
                ("challenge_id", models.CharField(db_index=True, max_length=64, unique=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("expires_at", models.DateTimeField()),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                ("failed_attempts", models.PositiveIntegerField(default=0)),
                ("locked_until", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="two_factor_challenges", to="accounts.user")),
            ],
        ),
        migrations.AddIndex(
            model_name="usertwofactorchallenge",
            index=models.Index(fields=["user", "flow"], name="accounts_us_user_id_7e0f40_idx"),
        ),
        migrations.AddIndex(
            model_name="usertwofactorchallenge",
            index=models.Index(fields=["expires_at"], name="accounts_us_expires_3a2fd8_idx"),
        ),
    ]
