# Generated by Django 5.2.12 on 2026-03-20 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_two_factor_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='usertwofactor',
            new_name='accounts_us_is_enab_2023ae_idx',
            old_name='accounts_usi_is_enab_aec89c_idx',
        ),
        migrations.RenameIndex(
            model_name='usertwofactorchallenge',
            new_name='accounts_us_user_id_ee45f5_idx',
            old_name='accounts_us_user_id_7e0f40_idx',
        ),
        migrations.RenameIndex(
            model_name='usertwofactorchallenge',
            new_name='accounts_us_expires_a930db_idx',
            old_name='accounts_us_expires_3a2fd8_idx',
        ),
    ]
