# Generated by Django 5.2.12 on 2026-03-21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_rename_accounts_usi_is_enab_aec89c_idx_accounts_us_is_enab_2023ae_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserTwoFactorBackupCode",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code_hash", models.CharField(max_length=255)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="two_factor_backup_codes", to="accounts.user")),
            ],
        ),
        migrations.AddIndex(
            model_name="usertwofactorbackupcode",
            index=models.Index(fields=["user", "used_at"], name="accounts_us_user_id_93350b_idx"),
        ),
        migrations.AddIndex(
            model_name="usertwofactorbackupcode",
            index=models.Index(fields=["created_at"], name="accounts_us_created_04fa8a_idx"),
        ),
    ]
