# Generated by Django 5.2.12 on 2026-03-20 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_two_factor_backup_codes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='usertwofactorbackupcode',
            new_name='accounts_us_user_id_d24d99_idx',
            old_name='accounts_us_user_id_93350b_idx',
        ),
        migrations.RenameIndex(
            model_name='usertwofactorbackupcode',
            new_name='accounts_us_created_3e2db7_idx',
            old_name='accounts_us_created_04fa8a_idx',
        ),
    ]
