# Generated by Django 5.2.12 on 2026-03-20 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_accounts_us_user_id_93350b_idx_accounts_us_user_id_d24d99_idx_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserTwoFactorBackupCode',
        ),
    ]
