# Generated by Django 5.2.12 on 2026-03-28 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coupons', '0001_initial'),
        ('orders', '0001_initial'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponusage',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usages', to='orders.order'),
        ),
        migrations.AddField(
            model_name='couponusage',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usages', to='stores.store'),
        ),
        migrations.AddConstraint(
            model_name='bulkdiscount',
            constraint=models.UniqueConstraint(fields=('store', 'target_type', 'category', 'product', 'priority'), name='uniq_bulk_discount_store_target_priority'),
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.UniqueConstraint(fields=('store', 'code'), name='uniq_coupon_store_code'),
        ),
        migrations.AddConstraint(
            model_name='couponusage',
            constraint=models.UniqueConstraint(fields=('store', 'coupon', 'order'), name='uniq_coupon_usage_store_coupon_order'),
        ),
    ]
