# Generated by Django 5.2.12 on 2026-03-27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coupons", "0001_initial"),
        ("orders", "0006_stockrestorelog_remove_stock_restored"),
        ("products", "0002_remove_productvariant_stock_quantity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="code",
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AddField(
            model_name="coupon",
            name="per_user_max_uses",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Max successful usages per authenticated user within this store.",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="BulkDiscount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.CharField(db_index=True, editable=False, help_text="Non-sequential public identifier (e.g. bdk_xxx).", max_length=32, unique=True)),
                ("target_type", models.CharField(choices=[("category", "Category"), ("subcategory", "Subcategory"), ("product", "Product")], max_length=20)),
                ("discount_type", models.CharField(choices=[("percentage", "Percentage"), ("fixed", "Fixed amount")], max_length=20)),
                ("discount_value", models.DecimalField(decimal_places=2, max_digits=10)),
                ("priority", models.PositiveIntegerField(default=0)),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("category", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="bulk_discounts", to="products.category")),
                ("product", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="bulk_discounts", to="products.product")),
                ("store", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="bulk_discounts", to="stores.store")),
            ],
            options={
                "ordering": ["-priority", "-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("store", "target_type", "category", "product", "priority"),
                        name="uniq_bulk_discount_store_target_priority",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CouponUsage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.CharField(db_index=True, editable=False, help_text="Non-sequential public identifier (e.g. cpu_xxx).", max_length=32, unique=True)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("phone", models.CharField(blank=True, default="", max_length=20)),
                ("is_reversed", models.BooleanField(default=False)),
                ("reversed_at", models.DateTimeField(blank=True, null=True)),
                ("reverse_reason", models.CharField(blank=True, default="", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("coupon", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="usages", to="coupons.coupon")),
                ("order", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="coupon_usages", to="orders.order")),
                ("store", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="coupon_usages", to="stores.store")),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="coupon_usages", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("store", "coupon", "order"),
                        name="uniq_coupon_usage_store_coupon_order",
                    )
                ],
            },
        ),
    ]
