# Generated by Django 5.2.10 on 2026-01-23 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_delivery_area_order_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_area',
            field=models.CharField(blank=True, choices=[('inside', 'Inside Dhaka City'), ('outside', 'Outside Dhaka City')], default='inside', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
