# Generated by Django 5.2.10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderNumberCounter',
            fields=[
                ('id', models.PositiveIntegerField(default=1, primary_key=True, serialize=False)),
                ('next_value', models.PositiveBigIntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=20, null=True, unique=True),
        ),
    ]
