# Generated by Django 5.2.11 on 2026-03-13 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_order_number'),
        ('orders', '0009_alter_order_status'),
    ]

    operations = [
    ]
