# Generated by Django 5.2.10 on 2026-01-21 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available_sizes',
        ),
        migrations.AddField(
            model_name='product',
            name='sub_category',
            field=models.CharField(blank=True, choices=[('new', 'New In'), ('audio', 'Audio'), ('wearables', 'Wearables'), ('smart-home', 'Smart Home'), ('gaming', 'Gaming'), ('cameras', 'Cameras'), ('drones', 'Drones'), ('cases', 'Cases & Covers'), ('chargers', 'Chargers'), ('cables', 'Cables'), ('stands', 'Stands & Mounts'), ('screen-protectors', 'Screen Protectors'), ('bags', 'Bags & Sleeves')], db_index=True, max_length=30, null=True),
        ),
    ]
