# Generated by Django 5.2.10 on 2026-01-21 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_available_sizes_product_sub_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('gadgets', 'Gadgets'), ('accessories', 'Accessories')], db_index=True, max_length=20),
        ),
    ]
