# Generated by Django 5.2.10 on 2026-01-21 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_dynamic_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('image', models.ImageField(help_text='Brand logo or image to display on the brand card', upload_to='brands/')),
                ('redirect_url', models.URLField(help_text='URL to redirect users when they click on the brand card', max_length=500)),
                ('brand_type', models.CharField(choices=[('accessories', 'Accessories'), ('gadgets', 'Gadgets')], help_text='Determines which section the brand appears in on the homepage', max_length=20)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within the brand type section (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this brand is visible on the site')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'ordering': ['brand_type', 'order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order in navigation'),
        ),
    ]
