# Generated by Django 5.2.10 on 2026-01-23 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_brand_alter_category_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0, help_text='Available stock quantity for this product'),
        ),
    ]
